### ISSUE TITLE
More explicit explanation on rewards and testnet

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#101]
- [x] Testnet banner should be on every page
- [x] We should highlight something like `you are not earning rewards, this is testnet`, maybe as a modal so that the users will have click **I understand** button

**Comment by 1devNdogs** [comment]
I can add a `click event` to show an `Info Modal`, also, `on the first launch,` we can trigger this `instantly`.

- Title: **Non-Incentivized Testnet** + `Question icon`
- Description:   **Non-Incentivized** means that any **token** issued in this network has `NO real financial value`. 
- Checkbox: I understand. Any token **reward** received by **farming** has `NO real financial value`. 
- Button: Ok. I agree.

Let me add this new `Info Modal` and we can **update texts** before PR.

**Comment by 1devNdogs** [comment]
Also, @ImmaZoni, do we have any Subspace link related to this?
It would be useful to add an external link with more information on the non-incentivized network means.
