### ISSUE TITLE
Large memory consumption by frontend

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#104]
My desktop app is running for a few days now (laptop went to sleep a few times) and I noticed that `WebKitWebProcess` process consumed 1.5G or RAM. That is the process responsible for rendering UI on Linux.

I don't think for the complexity of the UI that we have 1.5G is reasonable. Might be some memory leak in Polkadot.js again, but either way it is much more than `subspace-desktop` process (which is node, farmer and Tauri's backend all combined, 359.1M).

Also maybe we can un-load UI somehow completely if app is minimized?

**Comment by ozgunozerk** [comment]
It also started to create inconvenience when building the application with `yarn build`. I had to increase the maximum allocated space for javascript to 8GB to not get build errors related to memory usage. Might be related to this.

**Comment by 1devNdogs** [comment]
I will check if we can do some UI un-load on minimize. 

I think several things can be checked on the `vue/quasar` and `Polkadot.js` side. As we have been advancing with the app I have been writing down some waiting for the moment to apply them.

- Check `Vue` components and correct use of: computed, mounted/unmounted, reactive data, event Emitter.
- `Polkadot.js` from `client.ts` could be improved in several ways:
     - Block subscription and event filter can be improved a lot.
     - On **Dashboard** mounted, the API for the public endpoint must be disconnected. 
     - If it is not a first launch app, again, the API for the public endpoint must be disconnected or maybe not initialized.
- Update Polkadot packages, fix any deprecated usage. 

I'd like to check this out after #103, to work on the latest versions of **tauri**.

**Comment by nazar-pc** [comment]
When things start, it is not so bad, under 300M consumed by the process. So if it uses over 5x of that something must be leaking over time I think.

**Comment by isSerge** [comment]
Can't reproduce on v0.6.3
