### ISSUE TITLE
App gets stuck on querying the server when server is unable to respond

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#121]
I faced a problem when starting a node again (I used it before) resulted in this:
<details>

![Знімок екрана з 2022-03-28 19-04-27](https://user-images.githubusercontent.com/928965/160464749-563846b1-2d99-4a64-bc43-174bcdfb3792.png)

</details>

It is just spinning forever doing nothing. According to empty logs, it doesn't even try to start node or farmer. It took me 3 attempts for app to actually start properly.

I'm still on 0.2.0 release and on Linux (even though I don't think this is something platform-specific). Must be racy initialization somewhere. Feel free to close if this was a known issue and already fixed in newer releases.

**Comment by ozgunozerk** [comment]
This was related to the same issue on WebSockets. It is fixed by Leo on the nginx side. If this problem arises again, let's reopen it. 
For now, seems to be solved

**Comment by nazar-pc** [comment]
Can app start if RPC endpoint is unavailable? If not then no, it is not solved.

**Comment by ozgunozerk** [comment]
I guess not, I see your point
