### ISSUE TITLE
keyboard shortcuts does not work

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#127]
`ctrl+c` or `crtl+v` and etc. are not working in the app (at least in dev mode)

**Comment by ozgunozerk** [comment]
May be related to #96 as well

**Comment by 1devNdogs** [comment]
Can you have a look at this? https://github.com/tauri-apps/tauri/issues/2397

For me, windows and linux got shortcuts working.

**Comment by ozgunozerk** [comment]
Thanks Leo, that looks promising, adding menu seems to be the right solutions, since the topbar menu is not working in mac as well. I think it will solve many problems at once for mac
