### ISSUE TITLE
Autolaunch added without any warning

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#136]
I just started subspace-desktop 0.2.2 and it added itself to autostart. I disabled it, closed without going through setup process and started again, it added itself to autostart again :angry: 

Not only it should ask the user, it should also remember the decision and not add new entries again and again on every start.

* [ ] Do not enable autostart without permission
* [x] Remember decision and don't add autostart entry again and again

Maybe some of this was already fixed in `main`, I didn't check.

**Comment by ozgunozerk** [comment]
I discovered this issue and fixed it via #130 . Now it remembers the choice for autolaunch.
However, yes, we are not notifying the user about launching the app on start as the default choice.
