### ISSUE TITLE
Unable to select/detect pre-existing plotting folder

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#137]
When existing folder from older installation is selected on start, desktop app doesn't recognize that and shows plotting process that will supposedly run for days even though everything is already plotted and working just fine.

And the rest of UI is now blocked because "Dashboard will be available after initial plotting is finished" :disappointed:

**Comment by rg3l3dr** [comment]
Plan ahead

- [ ] store the user config in the plot folder
- [ ] on startup check if there is a plot: if plot, proceed to resync or final screen; if not, default startup
- [ ] create health check issue in subspace-monorepo
- [ ] implement the health check when plot is detected, if unhealthy, present message to user to reset plot in popup
