### ISSUE TITLE
App doesn't remember configuration

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#138]
Turns out #136 doesn't remember its settings because nothing is remembered in 0.2.2, on every restart I'm getting welcome screen.

**Comment by ozgunozerk** [comment]
Is this still the case? 

I just tried the most up to date main on MacOS, and it was not giving me the welcome screen after the first launch (tried couple of times).

**Comment by nazar-pc** [comment]
This is checked against 0.2.2 as stated in the first comment, I didn't check `main`.
