### ISSUE TITLE
public key/private key

### ISSUE THREAD

**Issue by trandinncuong** [subspace/subspace-desktop#148]
adding features: next version of subspace-desktop should include functions to let farmer insert his own public key, or retrieve public key/private key if they are created by subpace-desktop

**Comment by ImmaZoni** [comment]
Thank you so much for submitting your first issue with us! We definitely agree that this is a feature that needs to be added, luckily our amazing developers have been hard at work and actually already have this feature added :)

https://github.com/subspace/subspace-desktop/pull/132

Once we get it tested out and finalized, we will update it to the latest release, for now i'm going to close this issue.
