### ISSUE TITLE
Handle farmer exit gracefully

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#156]
If node is really slow, it is possible that farmer might exit on timeout.

For user this will look like stalled sync without clear steps what to do.

Farmer needs to either restart in a loop or at least show something to the user.

This must be related to some of the reports of stalled sync on Discord.

**Comment by ozgunozerk** [comment]
note to myself:
when solving this, also implement farmer stop and plotting stop functions

**Comment by rg3l3dr** [comment]
- [ ] expose stop plotting on the backend
- [ ] expose stop farming on the backend
- [ ] handle timeouts between farmer and node RPC backend
- [ ] ensure graceful shutdown procedure

**Comment by nazar-pc** [comment]
I've been running desktop app for over a week. I didn't receive a single coin and that is because farmer was dead since some point (confirmed by restarting and noticing that archiving on farmer is very active), but there was no indication of this in UI.

I think it is critical to at least restart farmer in the infinite loop if nothing else.

**Comment by nazar-pc** [comment]
@ozgunozerk this needs to get higher priority. At least restart in a loop, but it needs to be handled. Extra stuff can be added later.

**Comment by ozgunozerk** [comment]
My plan is to reflect the latest changes from monorepo to desktop, and fix this issue for tomorrow. Hopefully I will send 2 PRs :)
