### ISSUE TITLE
Estimating plot size stuck

### ISSUE THREAD

**Issue by trandinncuong** [subspace/subspace-desktop#161]
Ubuntu 20
Subspace desktop version 0.3.3
the app stuck at estimating plot size during setup plots process

**Comment by ozgunozerk** [comment]
There are 2 components to this problem:

1. main problem: server is unable to handle all the requests. We will scale the server (but that is outside the scope of subspace-desktop repo)
2. desktop app was not being efficient in sending requests to the Public RPC. We have optimized the desktop-app requests to the public RPC, it is currently under review: #160 

When this PR merges, and when we scale the server, this problem will be solved.

Thank you very much for this issue!

**Comment by ozgunozerk** [comment]
This is the duplicate of #121, let's track it there :)
