### ISSUE TITLE
Verbiage change for "no space"

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#172]
I have 18GB left on my ssd, so it says i have zero, wouldnt it be better to show my remaining storage accurately, and just still have the red ! warning and not let me proceed? 

Also, maybe an override button? (just an idea)

![image](https://user-images.githubusercontent.com/31865152/164767900-7377c497-63b0-4cad-9b71-87a12570b488.png)

**Comment by ozgunozerk** [comment]
This is not a bug, its intentionally made that way (node requires around 10-15 GB storage, and we set a 20 GB extra limit from the currently available space). We discussed showing this information but it would just confuse the users and also, we will switch to full-node from archival node very soon. Which means, this problem will be gone for good.
