### ISSUE TITLE
Show button is not displaying properly. 

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#173]
when the application is hidden and you attempt to show it from the task tray, it is adding characters in a random way

this is on Windows 10

![image](https://user-images.githubusercontent.com/31865152/164792666-87ab48e3-fd21-429c-90a1-28da9bad5a72.png)
![image](https://user-images.githubusercontent.com/31865152/164792715-bf0f8d9e-69c4-4c21-b6e5-0b73aac64db6.png)
![image](https://user-images.githubusercontent.com/31865152/164792799-9a0e9a6e-8b2b-4f90-9afc-6c0a61e5616b.png)

**Comment by ozgunozerk** [comment]
LOL that's weird, i will look into this, thanks!
Can you tell which version is that?

**Comment by ozgunozerk** [comment]
- [ ] Check if this issue present in 0.4.3 and 0.5.0
- [ ] if the bug is still present, debug it

**Comment by ozgunozerk** [comment]
This issue is not present in 0.4.7
Can you double-check @ImmaZoni before I close this?

**Comment by ImmaZoni** [comment]
![image](https://user-images.githubusercontent.com/31865152/167684589-4e0068f1-714f-4630-b8f0-f070b204554f.png)
yes, also present on hide now 

![image](https://user-images.githubusercontent.com/31865152/167684653-b1381fc8-fbd4-4a3f-8b2e-e7e320e4bcec.png)

**Comment by ozgunozerk** [comment]
Tried on 0.4.9 with clicking `hide` and `show` multiple times. Also `close` and `show` multiple times. Could not reproduce the issue (windows 10).

**Comment by ImmaZoni** [comment]
> Tried on 0.4.9 with clicking `hide` and `show` multiple times. Also `close` and `show` multiple times. Could not reproduce the issue (windows 10).

no longer showing up for me on 0.4.10, we can close for now.
