### ISSUE TITLE
show node name in the mainmenu

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#177]

**Comment by rg3l3dr** [comment]
@ozgunozerk can you provide screenshot here as well (before writing any code)

**Comment by ozgunozerk** [comment]
![image](https://user-images.githubusercontent.com/32795992/165291941-b9a51ef0-be30-47ca-af45-5d5f11916cc7.png)

Of course! We already discussed it at the meeting (where to put the node name). Changing the design (spacing and format) will be immediate to reflect code side as well :)
