### ISSUE TITLE
Show version of the app in the mainmenu

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#179]
This idea is from @Genysys . 
Usually, the version is not directly displayed in the applications (you have to click `about` from menu, etc.). 
But, we are currently testing/debugging the application, and users are usually providing screenshots. 

Displaying the version in the app may be a good idea for us to ease the process of debugging.
When the application is about to finalize (or when we proceed into version 1.x.x) we can remove this back.

**Comment by ozgunozerk** [comment]
Could look like this:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/32795992/165092306-161bcf09-6afc-42e6-a1e2-ab1d27f8dd8e.png">

what do you say @DianaPertseva @rg3l3dr @nazar-pc @ImmaZoni @isSerge ?

**Comment by isSerge** [comment]
I would put it somewhere else - users might think it is the Testnet version. 
Also, I would prefer simple text (without background), because this is a minor detail from the user's perspective. Maybe even hide it inside the menu (top right)

**Comment by ozgunozerk** [comment]
I agree it will create the false perception of testnet version instead of app version. Also agreed on without background, black text. 

However, the whole purpose of this change is to ease the debugging process, and users are sending screenshots. So we should not hide it I guess. 
As I mentioned in the beginning, the preferred location for this is under `menu -> about -> version` for the most applications. But that will probably be a later plan for our app

**Comment by nazar-pc** [comment]
Can we put it into application title, like "Subspace Desktop 0.4.1"?

Though I'm not sure this is a great idea to put it anywhere like that even though it is helpful for debugging.

**Comment by ozgunozerk** [comment]
I prefer mainmenu layout instead of application title (it would look ugly in the title imo, but will work for sure). 
I will send a new screenshot soon

**Comment by ozgunozerk** [comment]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/32795992/165160584-8e49a7e6-215b-4838-a19d-1064825d3e8c.png">
what about this?

**Comment by rg3l3dr** [comment]
@ozgunozerk looks good for now, we can make it prettier later.

Great job on posting here and tagging, let's continue to do that, but just one or two people, not the entire team.
