### ISSUE TITLE
Redirect logs to a file

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#181]
So that, our users can access the logs file.

**Comment by rg3l3dr** [comment]
- [ ] identify the logging framework or standard plugin from Tauri
- [ ] specify what logs we actually need to store
- [ ] ensure that logs are not persisted indefinitely and that there is cap on total log file size
- [ ] think about and propose a plan for how expose these logs to the user
- [ ] consider allow user to opt-in to log error reporting

**Comment by ozgunozerk** [comment]
There is an official tauri plugin for logging: https://github.com/tauri-apps/tauri-plugin-log
However, seems deprecated because releases are deleted and it is not on crate.io
I've contacted and waiting an answer from tauri team atm

**Comment by ozgunozerk** [comment]
They answered, it is not deprecated, just not released yet. 
We will be using it via specifying revisions in our `cargo.toml`.

- [ ] update tauri dependencies before using the native plugin for logging

**Comment by nazar-pc** [comment]
>  I've contacted and waiting an answer from tauri team atm

Please link to conversation next time, so it is easier to track it
