### ISSUE TITLE
Receive peers and block information from node

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#182]
Right now, frontend queries the localApi/publicApi for extracting the `peers` and `block` information. 

Frontend can receive these from backend (node) directly, this would also simplify the code (less connection requests on the frontend side)

**Comment by rg3l3dr** [comment]
Document which features require the WS connection to the RPC node, and if those can be done locally instead.
Migrate the requests from the front-end to the back-end, if there are any.

**Comment by isSerge** [comment]
@rg3l3dr @ozgunozerk 
public RPC endpoint is used for the following queries:
- get the latest block number from the chain (to know how many blocks to sync). This can be replaced by `api.rpc.system.syncState` query to local node
- get segments count (`api.query.subspace.counterForRecordsRoot`). We only display segments count during the initial plotting progress. Alternatively, we can just show synced blocks / total blocks and get rid of the public RPC endpoint. I don't think users care about the number of segments, but this is something we can discuss.

**Comment by ozgunozerk** [comment]
> This can be replaced by api.rpc.system.syncState query to local node
that's great news.

For the segment count, yes I think we can discuss it
