### ISSUE TITLE
macOS not displaying seed module occasionally

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#183]
# System
**System:** Macbook Air 2020, M1 CPU, 8 GB Ram. 
**Operating System:** macOS Monterey - 12.2

## Subspace Desktop v0.4.1
Getting stuck on start plotting screen. 

# Expected
1. Click `start plotting`
2. Pop up asking to confirm creating directory, click `confirm`
3. Confirm Popup disappears
4. Pop up showing seed automatically shows up next, etc. 
5. Progresses to next screen. 

# What im getting
1. Click `start plotting`
2. Pop up asking to confirm creating directory, click `confirm`
3. Confirm Pup disappears
4. .... nothing, no popup no next screen, if i click start plotting again it shows the confirm directory pop up again.

**Comment by ozgunozerk** [comment]
This is know, but great that you reported in detail. It is fixed, but not been released yet

**Comment by ImmaZoni** [comment]
@ozgunozerk is this fixed in v0.4.3? I am still getting it on some devices? (Windows in this case)
