### ISSUE TITLE
Define the correct scope of the update progress

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#185]
This will be a stepping stone for some other issues we currently have.

**Comment by ozgunozerk** [comment]
Our current strategy is not to store an external config file but to keep these information in the application (and when the application is deleted, config info is gone with it). 

If we want to handle breaking changes in the code, we have to move this config info outside of the application (probably to file system)

**Comment by achiurizo** [comment]
I think this is related to #65?

**Comment by ozgunozerk** [comment]
Yes, seems like a duplicate
