### ISSUE TITLE
Banner Not on Correct Version #

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#188]
Banner on v0.4.2 still shows v0.4.1, maybe it would be best to import this value dynamically from the tauri.conf.json or something?

![image](https://user-images.githubusercontent.com/31865152/165861861-1c560dfe-bbfc-4987-bd29-76a2926c012f.png)

![image](https://user-images.githubusercontent.com/31865152/165861881-231bbe8d-a77f-4820-9fd6-496d3b9d838a.png)

**Comment by ozgunozerk** [comment]
oh yeah, thanks
