### ISSUE TITLE
Selecting new drive does not recalculate storage capacity. 

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#202]
Reported from Discord. See thread here: https://discord.com/channels/864285291518361610/973771960502870106/973933870091210852

# Issue
If the users starts subspace desktop, then selects a different drive it does not recalculate the storage of the new drive, and continues to show the space of the default drive. 

# Screenshots 
 
![image](https://user-images.githubusercontent.com/31865152/167958216-cc6aba0f-0324-4fca-9061-89b37a9e8db5.png)
![image](https://user-images.githubusercontent.com/31865152/167958229-43fb6271-e489-4241-8369-09b710262eab.png)

**Comment by ImmaZoni** [comment]
@ozgunozerk probably should include this in next release, users are having issues with it on gemini.

**Comment by js2667** [comment]
Will this be fixed? looks like it was noticed a month ago. Im having the same issues. pretty major problem for all GUI users.

**Comment by ozgunozerk** [comment]
@js2667 
We will focus on this as the next major step (version 0.7.x). 
Can't give an exact date about it, but it is definitely on our list. 
Also, i'd rather approach to this issue with the word `implement`, then `fix`. Because this is not a bug to be fixed. It has not been implemented yet :)

**Comment by js2667** [comment]
@ozgunozerk i understand but how can I farm,  only on my local drive?

**Comment by ozgunozerk** [comment]
Thats true. It is only supporting the drive that the OS is installed on at the moment. It may or may not work for other scenarios, they are not supported.
