### ISSUE TITLE
Linux and Windows Log file location

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#210]
@nazar-pc , you suggested we can use a more conventional place for storing our log file. 
We are currently using the choices of tauri team for the location of the log file. 
Here are their reasoning behind this preference:
https://github.com/tauri-apps/tauri-plugin-log/issues/51

We can have a discussion in here about this

**Comment by nazar-pc** [comment]
Looks like you can already do necessary customization with `LogTarget::Dir` (just need to make sure AppImage build still works after this).

**Comment by ozgunozerk** [comment]
Yes, nearly everything is customizable in this logging crate. The reason I did not take action is: in the discussion (link above), idea of *keeping every file related to the app in the same place* also seemed logical to me.

**Comment by nazar-pc** [comment]
> keeping every file related to the app in the same place

It will not and should not be the case. Configuration, data (plots and node's data in our case), logs, cache: all these things have canonical locations for a reason. Legacy way of putting everything under `.appname` in the root of user's home folder is bad practice and should be avoided.
