### ISSUE TITLE
Verification failed - no sincing

### ISSUE THREAD

**Issue by GMND** [subspace/subspace-desktop#244]
![изображение](https://user-images.githubusercontent.com/26802919/172037817-513e8c55-686d-4139-a15e-3e6bf9bc4e31.png)

**Comment by GMND** [comment]
After re-install app - no first syncing
![изображение](https://user-images.githubusercontent.com/26802919/172038400-5ebdcff3-ee59-482b-851a-76145222a374.png)

**Comment by GMND** [comment]
[subspace-desktop.log](https://github.com/subspace/subspace-desktop/files/8839433/subspace-desktop.log)

**Comment by ozgunozerk** [comment]
Closing, since this is an issue related to monorepo, it has nothing to do with desktop code.
