### ISSUE TITLE
Implement error pages for potential worst case scenarios

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#253]
Although happens extremely rarely, node can fail sometimes. And also, we cannot 100% guarantee that node will never crash in the future as well. 

At the moment, we don't have any error handling in the GUI for node failures (for farmer, we are restarting it when an error happens). 

- [ ] If node fails, we can simply show an error page or pop-up a modal, and put a button in there for `restart the node/application`. 
- [ ] As the first step, this `restart` button can call `relaunch()` function from tauri. Although it is not the best solution, it should cover the majority of the cases
- [ ] As the ultimate goal, we should restart only the node depending on the error

**Comment by isSerge** [comment]
Apart from node issues we also may have following errors:
- during plotting or syncing (for example #248)
- post sync (issues related to connection, disk space, blocks are not farmed, etc)

We can start with some standard error component that will let users know that smth is wrong (show icon and message) and provide some steps like:
1. check internet connection, VPN, etc.
2. check disk space
3. ...
4. restart button (if relevant)
5. contact team and share logs

**Comment by achiurizo** [comment]
I've added a basic mock for our initial error modal [in our figma](https://www.figma.com/file/XiYxe6jyCPWpOhS9QPibPy/Desktop-v0.6.3). For the time being, we can keep it simple and provide a modal like so:

* error title for the specific issue if possible
* error body containing specific information and/or resolution information and links to additional resources.

![image](https://user-images.githubusercontent.com/24772/179881932-150194a4-ded0-422b-9397-50dbfe1a0c37.png)

> contact team and share logs

Regarding this, let's add this in a later step as I'd like to organize how we can better streamline our error escalation process(and community testing flow as well).

**Comment by achiurizo** [comment]
:clipboard: https://www.figma.com/file/XiYxe6jyCPWpOhS9QPibPy/Desktop-v0.6.3?node-id=120%3A93

![image](https://user-images.githubusercontent.com/24772/180036239-ca9eeaf7-ba99-4fb1-88ca-3a264ac9e8dd.png)

After syncing up with @isSerge, made some minor fixes here to use our existing design systems, namely material UI and the material icon set here. Some caveats here:

* doesn't need to be pixel perfect
* Error code on the bottom isn't necessary but was demoing if we needed additional context to associate with the error title.
* cleaned up our button to leverage material UI buttons and generalized the action in this screen as `restart`. Open to modifications/button title changes.

**Comment by isSerge** [comment]
@achiurizo I think we can add generic resolution info as a body at this stage and later add specific ones for each error because at the moment I don't know what would be specific resolutions

**Comment by isSerge** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/13568875/181760953-0b13afdf-0360-4a2d-91b2-3eaa15aabdce.png">

@achiurizo let me know if body text is ok. also, I had to make the title aligned to the left, because there might be issues if the title is longer.

**Comment by achiurizo** [comment]
@isSerge I think that looks fine. Thanks!

**Comment by isSerge** [comment]
We have basic implementation now:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/13568875/182025295-7699b0bf-d1b8-4644-9062-f56ef2864abf.png">

Next steps could be:
- [ ] add specific resolutions for these cases: could not update or read the config file, could not start node, could not start farming, etc.
- [ ] add more details on how to contact team

**Comment by achiurizo** [comment]
#298
