### ISSUE TITLE
Best Block # Not showing in logs

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#260]
In the logs the best block # is coming through with some character errors, it is not showing the int. it should be. 

![image](https://user-images.githubusercontent.com/31865152/173390475-171e41ee-ab70-4244-8d52-bd36ac1077df.png)

**Comment by ozgunozerk** [comment]
Thanks for reporting this. I will experiment with the encoding options :)

**Comment by ImmaZoni** [comment]
![image](https://user-images.githubusercontent.com/31865152/173468522-685b0a96-3b75-49bc-b924-8f2785d0baa9.png)

![image](https://user-images.githubusercontent.com/31865152/173468558-cf126b2f-f7c0-4bcd-94c6-af2c531e349d.png)
