### ISSUE TITLE
Implement Unit Testing

### ISSUE THREAD

**Issue by achiurizo** [subspace/subspace-desktop#285]
:clipboard: https://vuejs.org/guide/scaling-up/testing.html#unit-testing
:clipboard: https://vitest.dev/guide/features.html (vue recommended)

We should add some unit tests to the project to jumpstart our automated testing pipeline for the project.

**Comment by isSerge** [comment]
- [ ] add Jest and related dependencies
- [ ] update GitHub workflow to include test run
