### ISSUE TITLE
AppImage Blacklisted Libraries during Build

### ISSUE THREAD

**Issue by aaronbgreenblatt** [subspace/subspace-desktop#29]
Building app-v0.0.2.1 (commit fe0325eb48c9e7f718cf5bd0a175ed77121d1dc5) or app-v0.0.2.0 (commit9000ae828dedaefe0f1030baa72de869091c712c) results in complaints about "Skipping deployment of blacklisted library" AppImage, when built on Ubuntu 20.04.3 LTS, kernel 5.4.0-91-generic, rustc version 1.53.0, npm version 8.1.2, node version 16.13.2.

I did find this thread on appimage.org, suggesting that I compile the image on an old, old version of Ubuntu LTS. (https://discourse.appimage.org/t/skipping-deployment-of-blacklisted-library/1747). (I haven't tried this yet)

Full console output from the build attached
[console.txt](https://github.com/subspace/subspace-desktop/files/7867121/console.txt)

**Comment by nazar-pc** [comment]
I don't think blacklisted files have anything to do here, the reason is at the end:
```
-- Running input plugin: gtk --
[gtk/stdout] /home/localadmin/subspace/subspace-desktop-app-v0.0.2.1/src-tauri/t                                      arget/release/bundle/appimage/linuxdeploy-plugin-gtk.sh: patchelf not found.
[gtk/stdout] Install patchelf then re-run the plugin.
ERROR: Failed to run plugin: gtk (exit code: 1)
Error: failed to bundle project

Caused by:
    Shell Scripting Error:`error running appimage.sh`
```

Did you install dependencies from the readme?

**Comment by aaronbgreenblatt** [comment]
Golly - I swear I can read. Sorry!

I did install the dependencies listed in the readme. I also had to install the following packages: patchelf and librsvg2-dev.

I'm running Ubuntu Server (no GUI), so presumably those packages are included in ubuntu-desktop.

Is it worth updating the readme with these extra pacakges?

**Comment by nazar-pc** [comment]
I don't have `patchelf` or `librsvg2-dev` on my machine and I was able to build it before, we also don't install them in CI, but maybe it is there by default.

**Comment by nazar-pc** [comment]
So were you able to build it successfully in the end?

**Comment by aaronbgreenblatt** [comment]
Yes, to clarify my last comment, adding the patchelf and librsvg2-dev packages let me build the client successfully.
