### ISSUE TITLE
Windows 10 installation images are incorrectly sized. 

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#4]
## Description

The windows installation Icon and the Tasktray icons are both not sizing correctly, and are very pixelated. 

## Expected Behavior

Non-pixelated and correctly sized images

## Actual Behavior

Super pixelated images and sizing is off, the rest of the program works as expected. 

## Possible Fix

Correct sizing and pixel density of images
Correct code handling of images may it be an SVG/png/jpeg etc. 

## Context

Black logo is bad for dark mode, but we cant do white as it may cause issues on light mode, maybe some kind of off white, or off black/grey may be the best bet. 

## Steps to Reproduce

1. Install on windows 10 in dark mode.

## Your Environment

* Version used: v0.0.2
* Operating System and version: Windows 10
* Desktop, Laptop, or Server: Laptop

**Comment by ozgunozerk** [comment]
![Screenshot 2022-02-02 131623_LI](https://user-images.githubusercontent.com/32795992/152135468-1cc8bf6f-f1b5-42b5-a7bb-4ca21e773aed.jpg)

On my dark-windows10 machine, here is the result. Just to be clear, you are referring to parts circled with **red** and **yellow** in the screenshot, right?

Imo, only the **red** part is problematic.

**Comment by ImmaZoni** [comment]
Initially it was all 3 that had the issue. It is no longer present on my machine either, I will confirm with Diana if issue is resolved on her end. (She initially reported it)

**Comment by ozgunozerk** [comment]
@DianaPertseva @ImmaZoni 
Should we close this? Is the bug still present in your machines?
