### ISSUE TITLE
Utilize Tauri Sidecar functionality for Node support.

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#43]
Just a suggestion that may help out integrating the Node into the Subspace-Desktop app.

Tauri Sidecar - https://tauri.studio/docs/building/sidecar

**Comment by ozgunozerk** [comment]
Thanks Justin, that seems really promising!

**Comment by ozgunozerk** [comment]
Will use the normal way instead of this (just importing the node and running it in a separate thread). 
Thanks anyway Justin!
