### ISSUE TITLE
Fetching network data takes too long

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#47]
We have to somehow reduce this time, it may make the users think that application is stuck. 
Also, if possible, we should make it close to instant. So that we can use this information on replacing the default 10 GB for `Allocated` size and displaying the actual amount of space that will be used by the protocol.

**Comment by 1devNdogs** [comment]
Changed the way the plotting progress works.

Once we land on Plotting Progress
1.- Wait for fully synced local node, using polkadot API to query local node and remote public RPC. 
Showing the Block Syncing progress. with latest local block and latest network node.

2.- After the local node is fully synced, we query the public RPC to get the latest network segment index.
(Here was the problem that takes too long) 
It now takes less time, we scan for this data block by block until a RootBlockStored event is found.
Before it was waiting an event that sometimes takes minutes. Actually in a local dev networks could take a lot.
 
About the allocated size, think we have a way to do it. Let me check and discuss it on the corresponding [issue](https://github.com/subspace/subspace-desktop/issues/44). Want to close the plotting progress and linux build branches first.
