### ISSUE TITLE
Do not allow the user to open multiple farmers.

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/subspace-desktop#59]
Due to how we hide the process with the X button instead of closing it, I suggest we give a warning if the user tries to open the program with another instance already running. I personally have made this error, so it will likely be a cause of issue with general consumers.

**Comment by ozgunozerk** [comment]
I did a bit of research, found this (an unanswered discussion): https://github.com/tauri-apps/wry/discussions/336

I think there is no native support for this functionality at the moment from the tauri side. 

I also started another discussion in here: https://github.com/tauri-apps/tauri/discussions/3557

We may have to implement this ourselves without native support though.

**Comment by ozgunozerk** [comment]
Promising community projects for single instance:
https://gitlab.com/ioneyed/tauri-example-singleinstance
https://gitlab.com/ioneyed/tauri-plugin-highlander

**Comment by ozgunozerk** [comment]
By double-clicking the icon of the app, user is unable to start another instance. It is by default showing the current instance. So I guess, we got it covered by the default behaviour.

I will close this, if there are no objections from your side @ImmaZoni ?
