### ISSUE TITLE
Tauri updater feature - to handle version updates distribution.

### ISSUE THREAD

**Issue by 1devNdogs** [subspace/subspace-desktop#65]

**Comment by ozgunozerk** [comment]
What we want in ideal scenario is:
- when the app starts, it should check for updates
- if there are no updates, it shall continue as normal
- if there is an update present, it should prompt the user for whether they want to upgrade their software
- if the user approves, it shall update itself via downloading and auto-starting the installer
- if the user declines, it shall continue as normal

**Comment by isSerge** [comment]
@ozgunozerk I think we should also query if there is an update periodically because users might start the app only once and let it run for weeks until they face an issue

**Comment by ozgunozerk** [comment]
Yes, let me edit the above list, thank you!

**Comment by isSerge** [comment]
As for the update server, we can use gist (it may look like [this](https://gist.githubusercontent.com/lemarier/6bc28d06b94958d83eaa2790eef03f32/raw)), but if we have tens of thousands of users it could become a bottleneck, especially if we query periodically (not just on launch), so we would probably need a proxy. @nazar-pc what do you think?

**Comment by nazar-pc** [comment]
I think it would be preferred to either keep it in the repo or even in a separate S3 bucket or something that is automatically kept up to date.
We could also automate things by pushing into custom branch like it is used with `gh-pages` for statically generated HTML.

**Comment by nazar-pc** [comment]
I think periodic in our case means once per hour of a few times per day, right?

**Comment by ozgunozerk** [comment]
I think so, 1-2 times per day should be enough

**Comment by ImmaZoni** [comment]
> I think so, 1-2 times per day should be enough

Periodic updates should be no issue, the built in tauri updater has a events function to listen for new updates https://tauri.app/v1/guides/distribution/updater#events

**Comment by isSerge** [comment]
1. we show update dialog on launch
2. we check new updates and show same dialog if there is a newer version

Probably we also need smth like "Install update" button in the settings dropdown (in case the user closed the dialog previously)
