### ISSUE TITLE
Maximize the app from the tray when launcher is double clicked

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#76]
Right now, double-clicking the launcher does not initiate multiple instances, which is good.
But when the app is minimized, it does not get maximized when launcher is double-clicked.

**Comment by ozgunozerk** [comment]
let's focus this issue after we upgrade the tauri. From what I've researched, window methods are changed. Our time spent on this may be in vain if we do not wait for the upgrade.

**Comment by rg3l3dr** [comment]
Only on mac, @ozgunozerk retest and report

**Comment by ozgunozerk** [comment]
Retested, seems like it got fixed on its own. 
Works like other mac apps to my eyes.
