### ISSUE TITLE
Connect mnemonic into the wallet

### ISSUE THREAD

**Issue by ozgunozerk** [subspace/subspace-desktop#78]
We are not storing the mnemonic for security purposes, but we can encrypt it using the user-password. 
This could be the default option, and not storing the mnemonic could be an advanced option. 

If we decide to store the mnemonic, we should be able connect it to a wallet

**Comment by ozgunozerk** [comment]
Previously, we were storing the mnemonic of the farmer's signing key.
But now, we are only dealing with reward address on the frontend and we do not care about farmer's signing key/s. 

So, this issue is about :
- [ ]  connecting the seed phrase generated on the frontend, to a wallet application.


P.S:
We should also think about importing the reward address from a wallet via a better integration in a separate issue

**Comment by rg3l3dr** [comment]
Look at grammarly type experience between desktop app and web app hand off.
