### ISSUE TITLE
Can't specify folder that doesn't exist

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#87]
When starting an app, default directory is `/home/nazar-pc/.subspace-desktop-farmer`. It, obviously, doesn't exist initially.

However as soon as I change it to anything, let's say `/home/nazar-pc/.subspace-desktop-farmer2` it says "Invalid Directory".

This doesn't make sense and is a bug. It is can create a directory that is one level deep from existing by default, it should be capable of creating custom directories as well.

**Comment by ozgunozerk** [comment]
Yes, the behaviour is conflicting I agree. It can create the directory for the default path, but for any other folder, it expects that folder to be there. We can fix this easily, thanks for pointing that out. I had forgotten about it.

**Comment by nazar-pc** [comment]
No directories need to be created until confirmed by user IMHO, otherwise garbage empty directory will be left, see #88 and #85
