### ISSUE TITLE
Debian package broken

### ISSUE THREAD

**Issue by nazar-pc** [subspace/subspace-desktop#89]
Doesn't appear to be a package at all:
```
nazar-pc@nazar-pc:/fast-crap> LANG=C sudo dpkg -i subspace-desktop_0.2.0_amd64.deb
dpkg-deb: error: 'subspace-desktop_0.2.0_amd64.deb' is not a Debian format archive
dpkg: error processing archive subspace-desktop_0.2.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 subspace-desktop_0.2.0_amd64.deb
```

**Comment by ozgunozerk** [comment]
I believe Leo tested in his machine, and yesterday I tested this on my machine. 
After the command `yarn build`, I was able to run `.deb` package, and also it was syncing and working correctly as expected. 
I believe, this is again related to CI script, not related to source code. 
Will inspect further today.

**Comment by nazar-pc** [comment]
Deb package works fine on Ubuntu 21.10 :+1:
